version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: terranest-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: terranest
    volumes:
      - mongodb_data:/data/db
    networks:
      - terranest-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: terranest-backend
    restart: unless-stopped
    ports:
      - "5004:5004"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password@mongodb:27017/terranest?authSource=admin
      - JWT_SECRET=your_production_jwt_secret_here
      - PORT=5004
    depends_on:
      - mongodb
    networks:
      - terranest-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: terranest-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5004
      - REACT_APP_API_BASE_URL=http://localhost:5004/api
    depends_on:
      - backend
    networks:
      - terranest-network

volumes:
  mongodb_data:

networks:
  terranest-network:
    driver: bridge